openapi: 3.0.1
info:
  title: QuestBook Data Validator
  version: 0.1.0
  description: Validates data, uploads & pins it to IPFS
servers:
  - url: http://localhost:3001
    description: Local server
  - url: https://api-grant-validator.questbook.app
    description: Production server
paths:
  /validate/grant-create:
    post:
      operationId: validateGrantCreate
      summary: Validate, upload & pin grant to IPFS
      tags:
        - Validation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrantCreateRequest'
      responses:
        '200':
          $ref: '#/components/responses/ValidationSuccessResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /validate/workspace-create:
    post:
      operationId: validateWorkspaceCreate
      summary: Validate, upload & pin workspace data to IPFS
      tags:
        - Validation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkspaceCreateRequest'
      responses:
        '200':
          $ref: '#/components/responses/ValidationSuccessResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
  /validate/grant-application:
    post:
      operationId: validateGrantApplication
      summary: Validate, upload & pin grant application data to IPFS
      tags:
        - Validation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrantApplicationRequest'
      responses:
        '200':
          $ref: '#/components/responses/ValidationSuccessResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    Error:
      type: object
      required:
        - statusCode
        - error
        - message
      properties:
        statusCode:
          type: number
          minimum: 200
          maximum: 505
        error:
          type: string
          description: Specific description of the error
        message:
          type: string
          description: What the error was
        data:
          type: object
          description: Some extra information about the error
    SupportedNetwork:
      type: string
      description: ID of the network
      example: '0x95b58a6bff3d14b7db2f5cb5f0ad413dc2940658'
    GrantField:
      type: object
      additionalProperties: false
      required:
        - id
        - title
        - inputType
      properties:
        id:
          type: string
          maximum: 255
        title:
          description: Human readable title of the field
          type: string
        inputType:
          enum:
            - short-form
            - long-form
            - numeric
        enum:
          description: Constraint possible inputs for this field
          type: array
          items:
            type: string
    GrantFieldAnswer:
      type: array
      items:
        required:
          - id
          - value
        properties:
          id:
            type: string
            maximum: 255
          value:
            type: string
    GrantProposedMilestone:
      type: object
      required:
        - title
        - amount
      properties:
        title:
          type: string
        amount:
          type: number
    GrantApplicationRequest:
      type: object
      additionalProperties: false
      required:
        - grantId
        - applicantId
        - details
        - fields
        - members
      properties:
        grantId:
          type: string
        applicantId:
          $ref: "#/components/schemas/OwnerID"
        details: 
          type: string
          maximum: 10000
        fields:
          type: array
          maximum: 100
          items:
            $ref: "#/components/schemas/GrantFieldAnswer"
        members:
          type: array
          maximum: 100
          items:
            type: object
            additionalProperties: false
            required:
              - details
            properties:
              details:
                type: string
        milestones:
          type: array
          maximum: 100
          items:
            $ref: "#/components/schemas/GrantProposedMilestone"
    WorkspaceCreateRequest:
      type: object
      additionalProperties: false
      required:
        - title
        - about
        - logoIpfsHash
        - creatorId
        - supportedNetworks
      properties:
        title:
          type: string
          minimum: 5
          maximum: 128
        about:
          type: string
          minimum: 5
          maximum: 4096
        logoIpfsHash:
          type: string
          description: IPFS hash of the logo of the workspace
        creatorId:
          $ref: "#/components/schemas/OwnerID"
        supportedNetworks:
          type: array
          maximum: 100
          items:
            $ref: "#/components/schemas/SupportedNetwork"
    GrantCreateRequest:
      type: object
      additionalProperties: false
      required:
        - title
        - summary
        - details
        - amount
        - creatorId
        - workspaceId
        - fields
      properties:
        title:
          type: string
          minimum: 5
          maximum: 255
        summary:
          type: string
          minimum: 5
          maximum: 1024
        details:
          type: string
          minimum: 50
        deadline:
          type: string
          format: date-time
          description: Deadline of the application
        amount:
          type: object
          additionalProperties: false
          required:
            - value
            - network
          properties:
            value:
              type: number
              minimum: 0.001
              example: 10.5
            network:
              $ref: "#/components/schemas/SupportedNetwork"
        creatorId:
          $ref: "#/components/schemas/OwnerID"
        workspaceId:
          type: string
          description: the workspace the grant is from
        fields:
          type: array
          minimum: 1
          maximum: 100
          items:
            $ref: "#/components/schemas/GrantField"
    OwnerID:
      type: string
      minimum: 16
      maximum: 255
      example: '0x71C7656EC7ab88b098defB751B7411C5f6d8976F'
  responses:
    ValidationSuccessResponse:
      description: Validation was success, data pushed to IPFS & pinned
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            required:
              - ipfsHash
              - url
            properties:
              ipfsHash:
                type: string
                description: IPFS hash of the uploaded grant
                example: QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco
              url:
                type: string
                description: http url that can be used to fetch the uploaded grant file
                example: https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco
    ErrorResponse:
      description: Generic error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"