/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/validate/grant-create": {
    post: operations["validateGrantCreate"];
  };
  "/validate/grant-update": {
    post: operations["validateGrantUpdate"];
  };
  "/validate/workspace-create": {
    post: operations["validateWorkspaceCreate"];
  };
  "/validate/workspace-update": {
    post: operations["validateWorkspaceUpdate"];
  };
  "/validate/grant-application-create": {
    post: operations["validateGrantApplicationCreate"];
  };
  "/validate/grant-application-update": {
    post: operations["validateGrantApplicationUpdate"];
  };
}

export interface components {
  schemas: {
    Error: {
      statusCode: number;
      /** @description Specific description of the error */
      error: string;
      /** @description What the error was */
      message: string;
      /** @description Some extra information about the error */
      data?: { [key: string]: unknown };
    };
    /**
     * @description ID of the network
     * @example 0x95b58a6bff3d14b7db2f5cb5f0ad413dc2940658
     */
    SupportedNetwork: string;
    GrantField: {
      id: string;
      /** @description Human readable title of the field */
      title: string;
      inputType: "short-form" | "long-form" | "numeric";
      /** @description Constraint possible inputs for this field */
      enum?: string[];
    };
    GrantFieldAnswer: {
      id: string;
      value: string;
    };
    GrantProposedMilestone: {
      title: string;
      amount: number;
    };
    GrantApplicationRequest: {
      grantId: string;
      applicantId: components["schemas"]["OwnerID"];
      details: string;
      fields: components["schemas"]["GrantFieldAnswer"][];
      members: {
        details: string;
      }[];
      milestones?: components["schemas"]["GrantProposedMilestone"][];
    };
    GrantApplicationUpdate: {
      details?: string;
      milestones?: components["schemas"]["GrantProposedMilestone"][];
    };
    SocialItem: {
      name: string;
      value: string;
    };
    WorkspaceCreateRequest: {
      title: string;
      about: string;
      /** @description IPFS hash of the logo of the workspace */
      logoIpfsHash: string;
      /** @description IPFS hash of the cover of the workspace */
      coverImageIpfsHash?: string;
      creatorId: components["schemas"]["OwnerID"];
      supportedNetworks: components["schemas"]["SupportedNetwork"][];
      socials: components["schemas"]["SocialItem"][];
    };
    WorkspaceUpdateRequest: {
      title?: string;
      about?: string;
      /** @description IPFS hash of the logo of the workspace */
      logoIpfsHash?: string;
      /** @description IPFS hash of the cover of the workspace */
      coverImageIpfsHash?: string;
      socials?: components["schemas"]["SocialItem"][];
    };
    GrantCreateRequest: {
      title: string;
      summary: string;
      details: string;
      /**
       * Format: date-time
       * @description Deadline of the application
       */
      deadline?: Date | string;
      reward: {
        /** @example 10.5 */
        committed: number;
        asset: components["schemas"]["SupportedNetwork"];
      };
      creatorId: components["schemas"]["OwnerID"];
      /** @description the workspace the grant is from */
      workspaceId: string;
      fields: components["schemas"]["GrantField"][];
    };
    GrantUpdateRequest: {
      details?: string;
      /**
       * Format: date-time
       * @description Deadline of the application
       */
      deadline?: Date | string;
      fields?: components["schemas"]["GrantField"][];
    };
    /** @example 0x71C7656EC7ab88b098defB751B7411C5f6d8976F */
    OwnerID: string;
  };
  responses: {
    /** Validation was success, data pushed to IPFS & pinned */
    ValidationSuccessResponse: {
      content: {
        "application/json": {
          /**
           * @description IPFS hash of the uploaded grant
           * @example QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco
           */
          ipfsHash: string;
          /**
           * @description http url that can be used to fetch the uploaded grant file
           * @example https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco
           */
          url: string;
        };
      };
    };
    /** Generic error response */
    ErrorResponse: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
}

export interface operations {
  validateGrantCreate: {
    responses: {
      200: components["responses"]["ValidationSuccessResponse"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GrantCreateRequest"];
      };
    };
  };
  validateGrantUpdate: {
    responses: {
      200: components["responses"]["ValidationSuccessResponse"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GrantUpdateRequest"];
      };
    };
  };
  validateWorkspaceCreate: {
    responses: {
      200: components["responses"]["ValidationSuccessResponse"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkspaceCreateRequest"];
      };
    };
  };
  validateWorkspaceUpdate: {
    responses: {
      200: components["responses"]["ValidationSuccessResponse"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkspaceUpdateRequest"];
      };
    };
  };
  validateGrantApplicationCreate: {
    responses: {
      200: components["responses"]["ValidationSuccessResponse"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GrantApplicationRequest"];
      };
    };
  };
  validateGrantApplicationUpdate: {
    responses: {
      200: components["responses"]["ValidationSuccessResponse"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GrantApplicationUpdate"];
      };
    };
  };
}

export interface external {}
