/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/validate": {
    post: operations["validate"];
  };
}

export interface components {
  schemas: {
    Error: {
      statusCode: number;
      /** @description Specific description of the error */
      error: string;
      /** @description What the error was */
      message: string;
      /** @description Some extra information about the error */
      data?: { [key: string]: unknown };
    };
    GrantReleaseType: "single" | "milestone";
    GrantApplication: {
      title: string;
      description: string;
      amount: {
        /** @example 10.5 */
        value: number;
        /** @example ETH */
        token: string;
      };
      releaseType: components["schemas"]["GrantReleaseType"];
      ownerId: components["schemas"]["OwnerID"];
    };
    /** @example 0x71C7656EC7ab88b098defB751B7411C5f6d8976F */
    OwnerID: string;
  };
  responses: {
    /** Validation was success, data pushed to IPFS & pinned */
    ValidationSuccessResponse: {
      content: {
        "application/json": {
          /** @example QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco */
          ipfsHash: string;
          /**
           * Format: uri
           * @example https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco
           */
          url: string;
        };
      };
    };
    /** Generic error response */
    ErrorResponse: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
}

export interface operations {
  validate: {
    responses: {
      200: components["responses"]["ValidationSuccessResponse"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GrantApplication"];
      };
    };
  };
}

export interface external {}
